config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :redactor do
    resources :pictures, :only => [:index, :create]
  end

  unless Rails.env.production?
    get "master_login" => "pages#master_login"
  end

  root 'pages#home'
  get 'pages/temporary' => 'pages#temporary'

  resources :contents do
    get 'search', on: :collection
    get 'tags', on: :collection
  end

  resources :videos do
    get 'download'
  end
  resources :audios do
    get 'download'
  end
  resources :images do
    get 'download'
  end
  resources :remixes do
    get 'download'
  end
  resources :warnings
  resources :posts

  resources :pages do
    post :change_user_session
  end

  namespace :admin do
    resources :users
    resources :user_activities
    resources :posts
    resources :warnings
    resources :videos  do
      put 'toggle_main'
      put 'toggle_open'
      get 'remote_videos', on: :collection
      post 'fetch_selected_remote_videos', on: :collection
      post 'fetch_remote_video', on: :collection
    end
    resources :audios  do
      get 'remote_audios', on: :collection
      post 'fetch_selected_remote_audios', on: :collection
      post 'fetch_remote_audio', on: :collection
      put 'toggle_main'
      put 'toggle_open'
    end
    resources :images  do
      get 'remote_images', on: :collection
      post 'fetch_selected_remote_images', on: :collection
      post 'fetch_remote_image', on: :collection
      put 'toggle_main'
      put 'toggle_open'
    end
    resources :contents
    resources :categories
    root 'videos#index'
  end

end

app/models/content.rb
#encoding: utf-8
require 'rest_client'
require 'json'
# require 'google/api_client'
# require 'google/api_client/auth/installed_app'

class Content < ActiveRecord::Base
  acts_as_taggable # Alias for acts_as_taggable_on :tags

  belongs_to :user
  has_many :user_activities
  has_many :warnings, dependent: :destroy

  validates :title, presence: true
  # validates :copyright, presence: true

  serialize :source_info
  serialize :parent_content_ids

  after_initialize do
    if parent_content_ids.nil?
      parent_content_ids = []
    end
  end

  before_validation do
    if self.is_remix == false
      self.parent_content_ids = []
    end
  end

  before_validation :adjust_copyright

  attr_accessor :copyright_extra
  COPYRIGHT = ["CC BY (저작자표시)", "CC BY-NC (저작자표시 비영리)", "CC BY-ND (저작자표시 변경금지)", "CC BY-SA (저작자표시 동일조건변경허락)", "CC BY-NC-SA (저작자표시 비영리 동일조건변경허락)", "CC BY-NC-ND (저작자표시 비영리 변경금지)", "CC0 (저작권 포기)", "public domain (저작권이 소멸된 저작물)" ]

  COPYRIGHT_IMAGE_HASH = {
    Content::COPYRIGHT[0] => [
      "https://i.creativecommons.org/l/by/4.0/88x31.png",
      "http://creativecommons.org/licenses/by/4.0/"
      ],
    Content::COPYRIGHT[1] => [
      "https://i.creativecommons.org/l/by-nc/4.0/88x31.png",
      "http://creativecommons.org/licenses/by-nc/4.0/"
      ],
    Content::COPYRIGHT[2] => [
      "https://i.creativecommons.org/l/by-nd/4.0/88x31.png",
      "http://creativecommons.org/licenses/by-nd/4.0/"
      ],
    Content::COPYRIGHT[3] => [
      "https://i.creativecommons.org/l/by-sa/4.0/88x31.png",
      "http://creativecommons.org/licenses/by-sa/4.0/"
      ],
    Content::COPYRIGHT[4] => [
      "https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png",
      "http://creativecommons.org/licenses/by-nc-sa/4.0/"
      ],
    Content::COPYRIGHT[5] => [
      "https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png",
      "http://creativecommons.org/licenses/by-nc-nd/4.0/"
      ],
    Content::COPYRIGHT[6] => [
      "http://i.creativecommons.org/p/zero/1.0/88x31.png",
      "https://creativecommons.org/choose/zero/"
      ],
    Content::COPYRIGHT[7] => [
      "http://i.creativecommons.org/p/mark/1.0/88x31.png",
      "https://creativecommons.org/choose/mark/"
      ]
  }

  def copy_right_image_url
    if self.extra_copyright
      self.copyright
    else
      COPYRIGHT_IMAGE_HASH[self.copyright].try(:[], 0)
    end
  end

  def copy_right_licence_info_url
    if self.extra_copyright
      '#'
    else
      COPYRIGHT_IMAGE_HASH[self.copyright].try(:[], 1)
    end
  end

  def adjust_copyright
    if extra_copyright
      self.copyright = copyright_extra
    else
      self.copyright = self.copyright
    end
  end

  def self.in_copyright(copyright)
    if copyright.present?
      where(copyright: copyright)
    else
      all
    end
  end

  def self.in_query(q)
    if q.present?
      joins(:tags).where("tags.name like ? or title like ? or body like ? or copyright like ?","%#{q}%","%#{q}%","%#{q}%","%#{q}%")
    else
      all
    end
  end

  def self.in_title(title)
    if title.present?
      where('title like ?',"%#{title}%")
    else
      all
    end
  end

  def self.in_body(body)
    if body.present?
      where('body like ?',"%#{body}%")
    else
      all
    end
  end

  def self.in_author(author)
    if author.present?
      joins(:user).where("users.name like ?", "%#{author}%")
    else
      all
    end
  end

  def self.in_owner(owner_name)
    if owner_name.present?
      where('owner_name like ?',"%#{owner_name}%")
    else
      all
    end
  end

  def self.in_open(open)
    if open.present?
      open = (open == "true")
      where(is_open: open)
    else
      all
    end
  end

  def self.in_main(main)
    if main.present?
      main = (main == "true")
      where(main: main)
    else
      all
    end
  end

  def self.in_remix(remix)
    if remix.present?
      remix = (remix == "true")
      where(is_remix: remix)
    else
      all
    end
  end

  def increase_download_count(user)
    UserActivity.create(user_id: user.id, content_id: self.id)
    self.download_count += 1
    self.save
  end

  def self.popular
    # FIXME:  view + download_count 로 로직 수정 필요
    order('view ASC').limit(18)
  end

  def remix_ko
    self.is_remix? ? 'O' : 'X'
  end

  # def update_sns
    # facebook
    # me = FbGraph::User.me(ENV['YOUR_ACCESS_TOKEN'])
    # me = me.fetch
    # me.feed!(
    #   :message => '셀수스에 새로운 콘텐츠가 업데이트되었습니다.',
    #   :picture => self.thumbnail_url,
    #   :link => 'https://www.facebook.com/celsuscoop',
    #   :name => self.title,
    #   :description => self.body
    # )

    # twitter
    # client = TwitterOAuth::Client.new(
    #   :consumer_key => ENV['TWITTER_CONSUMER_KEY'],
    #   :consumer_secret => ENV['TWITTER_CONSUMER_SECRET'],
    #   :token => ENV['TWITTER_ACCESS_TOKEN'],
    #   :secret => ENV['TWITgit giTER_ACCESS_SECRET']
    # )
    # client.update('셀수스에 새로운 콘텐츠가 업데이트되었습니다.' + self.link)

    # google
    # client = Google::APIClient.new(
    #   :application_name => 'celsus',
    #   :application_version => '1.0.0'
    # )
    # plus = client.discovered_api('plus')

    # flow = Google::APIClient::InstalledAppFlow.new(
    #   :client_id => ENV['GOOGLE_CLIENT_ID'],
    #   :client_secret => ENV['GOOGLE_CLIENT_SECRET'],
    #   :scope => ['https://www.googleapis.com/auth/plus.me']
    #   # :redirect_uri => 'https://celsus.ufosoft.net/oauth2callback'
    # )
    # client.authorization = flow.authorize

    # # moment = {
    # #   "type": "http://schemas.google.com/AddActivity",
    # #   "target": {
    # #     "id": "target-id-1"
    # #     "url": "https://developers.google.com/+/plugins/snippet/examples/thing"
    # #     "name": "The Google+ Platform",
    # #     "description": "A page that describes just how awesome Google+ is!"
    # #   }
    # # }
    # result = client.execute(
    #   :api_method => plus.momenti.insert,
    #   :parameters => {'collection' => 'vault', 'userId' => 'me', 'body' => moment}
    # )
  # end

  def check_owner_url
    self.owner_url = "http://"+ self.owner_url unless self.owner_url.include? "http://"
    self.owner_url
  end
end

app/controllers/admin/contents_controller.rb
class Admin::ContentsController < AdminController
  def index
    @contents = Content.where(is_remix: true)
                       .in_title(params[:title])
                       .in_body(params[:body])
                       .in_owner(params[:owner_name])
                       .in_author(params[:author])
                       .in_remix(params[:remix])
                       .in_open(params[:open])
                       .in_main(params[:main])
                       .in_copyright(params[:copyright])
                       .order('created_at DESC').page(params[:page]).per(10)
  end
  def search
    @contents = Content.where(is_open: true).in_query(params[:q]).in_copyright(params[:copyright]).page(params[:page]).per(16)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
    @contents = Content.where(is_open: true)
  end

  def search
    @contents = Content.where(is_open: true).in_query(params[:q]).in_copyright(params[:copyright]).page(params[:page]).per(16)
  end

  def tags
    if params[:tag].present?
      @contents = Content.tagged_with(params[:tag]).page(params[:page]).per(16)
    end
  end

end

app/helpers/contents_helper.rb
module ContentsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/contents/_recent_remix.html.haml
.content-box
  %h4.content-box__title
    ="최신 리믹스"
  .content-box__imglist.content-imglist
    .img-list.als-container
      %span.als-prev
        = image_tag 'icon-arrow-left.png', alt: '왼쪽버튼'
      .als-viewport
        %ul.als-wrapper
          - Content.where(is_remix: true).order("created_at DESC").limit(10).each do |content|
            %li.als-item
              = link_to image_tag(content.thumbnail_url), content
      %span.als-next
        = image_tag 'icon-arrow-right.png', alt: '오른쪽버튼'
    .clearfix

app/views/contents/index.html.haml
%section
  .page-header
    %h2 Contents


%table.table.table
  %thead
    %tr
      %th
        %label 제목
      %th
        %label 본문
      %th
        %label 링크
  %tbody
    - @contents.each do |content|
      %tr
        %td
          = content.title
        %td
          = content.body
        %td
          = link_to content.link, content

app/views/contents/search.html.haml
.container
  .content-list-box
    .content-list-box__title
      ="'#{params[:q]}' 에 대한 검색 결과입니다."
    .content-list-box__list.clearfix
      - @contents.each_slice(4) do |contents|
        %ul.unstyled
          - contents.each do |content|
            %li
              =link_to content do
                .thumb{ style: "background-image: url(#{content.thumbnail_url})" }
              .pull-right
                %p= content.type
    .content-search.text-center
      = form_tag(search_contents_path, method: "get") do
        - content_copyright = Content.pluck(:copyright).uniq
        .search-wrapper.iblc
          = select_tag 'copyright', options_for_select(content_copyright, (params[:copyright] rescue '')), class: "selectpicker iblc", :prompt => "저작권을 선택해 주세요"
          = text_field_tag(:q, value=nil, options = {:value => params[:q], placeholder: '검색어', class: 'form-control content-search__form iblc'})
          = submit_tag "검색", class: 'btn btn-purple search-bar__submit_btn iblc'

    .content-list-box__paginate.text-center
      = paginate @contents if @contents.present?

app/views/contents/tags.html.haml
.container
  .content-list-box
    .content-list-box__title
      ="'#{params[:tag]}' 에 대한 태그입니다."
    .content-list-box__list.clearfix
      - @contents.each_slice(4) do |contents|
        %ul.unstyled
          - contents.each do |content|
            %li
              =link_to content do
                .thumb{ style: "background-image: url(#{content.thumbnail_url})" }
              %p.text-right= content.type



    .content-list-box__paginate.text-center
      = paginate @contents if @contents.present?