config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :redactor do
    resources :pictures, :only => [:index, :create]
  end

  unless Rails.env.production?
    get "master_login" => "pages#master_login"
  end

  root 'pages#home'
  get 'pages/temporary' => 'pages#temporary'

  resources :contents do
    get 'search', on: :collection
    get 'tags', on: :collection
  end

  resources :videos do
    get 'download'
  end
  resources :audios do
    get 'download'
  end
  resources :images do
    get 'download'
  end
  resources :remixes do
    get 'download'
  end
  resources :warnings
  resources :posts

  resources :pages do
    post :change_user_session
  end

  namespace :admin do
    resources :users
    resources :user_activities
    resources :posts
    resources :warnings
    resources :videos  do
      put 'toggle_main'
      put 'toggle_open'
      get 'remote_videos', on: :collection
      post 'fetch_selected_remote_videos', on: :collection
      post 'fetch_remote_video', on: :collection
    end
    resources :audios  do
      get 'remote_audios', on: :collection
      post 'fetch_selected_remote_audios', on: :collection
      post 'fetch_remote_audio', on: :collection
      put 'toggle_main'
      put 'toggle_open'
    end
    resources :images  do
      get 'remote_images', on: :collection
      post 'fetch_selected_remote_images', on: :collection
      post 'fetch_remote_image', on: :collection
      put 'toggle_main'
      put 'toggle_open'
    end
    resources :contents
    resources :categories
    root 'videos#index'
  end

end

app/models/video.rb
#encoding: utf-8
class Video < Content
  before_validation :adjust_remote_content_id
  before_validation :fetch_video_info

  validates :remote_content_id, :user_id, presence: true
  validate :unique_remote_content_id
  validate :source_info_fetched

  def self.popular
    # FIXME:  view + download_count 로 로직 수정 필요
    order('view ASC').limit(18)
  end

  def self.remote_videos(page: nil, per_page: nil)
    _page = page.presence || 1
    _per_page = per_page.presence || 20
    resp = RestClient.get("https://api.vimeo.com/me/videos?page=#{_page}&per_page=#{_per_page}", {"Authorization" => "bearer #{ENV['VIMEO_ACCESS_TOKEN']}"})
    hash = JSON.parse(resp)
    hash["data"].map do |video_data|
      video_data_id = video_data["uri"].split("/").last
      r_video = RemoteVideo.new(video_data)
      if Video.where(remote_content_id: video_data_id).present?
        r_video.already_taken = true
      end
      r_video
    end.compact
  rescue RestClient::BadRequest => e
    []
  end

  def self.create_from_remote(video_id, user_id)
    Video.create(user_id: user_id, remote_content_id: video_id)
  end

  def friendly_videos
    friendly_videos = []
    self.tag_list.each do |tag|
      friendly_videos << Video.where(is_open: true).tagged_with(tag)
    end
    friendly_videos.flatten.uniq - [self]
  end

  def license_match(license)
    _license = ''
    if(license.nil?)
      errors.add(:link, "저작권 승인이 안되는 컨텐츠 입니다.")
    elsif (license == 'by')
      _license = Content::COPYRIGHT[0]
    elsif (license == 'by-nc')
      _license = Content::COPYRIGHT[1]
    elsif (license == 'by-nd')
      _license = Content::COPYRIGHT[2]
    elsif (license == 'by-sa')
      _license = Content::COPYRIGHT[3]
    elsif (license == 'by-nc-sa')
      _license = Content::COPYRIGHT[4]
    elsif (license == 'by-nc-nd')
      _license = Content::COPYRIGHT[5]
    elsif (license == 'cc0')
      _license = Content::COPYRIGHT[6]
    end
    _license
  end

  def download_links_hash
    self.source_info["download"]
  end

  def download_url(type_quality, type_width)
    download_info = self.download_links_hash.select{|type| (type["quality"] == type_quality) && (type["width"] == type_width.to_i)}.first
    return if download_info.blank?

    expire_at = Time.parse(download_info["expires"])
    if expire_at < Time.now
      _set_video_info( _fetch_video_info )
      self.save
    end
    download_info = self.reload.download_links_hash.select{|type| type["quality"] == type_quality }.first
    download_info["link"]
  end

  def adjust_remote_content_id
    if link_changed?
      self.remote_content_id = self.link.split("/").last
    end
  end

  def fetch_video_info
    return if not remote_content_id_changed?
    resp_hash = _fetch_video_info
    return if resp_hash.blank?
    _set_video_info(resp_hash)
  end

  def unique_remote_content_id
    video = Video.where(remote_content_id: self.remote_content_id).last
    if video.present? && video.id != self.id
      errors.add(:link, "이미 존재하는 비디오 입니다.")
    end
  end

  def source_info_fetched
    if source_info.blank?
      errors.add(:link, '잘못된 주소이거나, 비디오 정보를 가져오는데 실패했습니다.')
    end
  end

  def _fetch_video_info
    request_url =  "https://api.vimeo.com/videos/#{self.remote_content_id}"
    resp = RestClient.get(request_url, {"Authorization" => "bearer #{ENV['VIMEO_ACCESS_TOKEN']}"} )
    JSON.parse(resp)
  rescue
    {}
  end

  def _set_video_info(resp_hash)
    self.source_info = resp_hash
    string = <<-RUBY
<iframe width="100%" height="400" scrolling="no" frameborder="no" src="//player.vimeo.com/video/#{self.remote_content_id}"></iframe>
RUBY
    self.iframe_html = string
    self.title = self.source_info["name"] if self.title.blank?
    _copyright = license_match(source_info["license"])
    self.copyright = _copyright if self.copyright.blank?
    self.link = self.source_info["link"]
  end

  def thumbnail_url
    source_info['pictures'].select {|p| p['width'] == 295 }.first["link"]
  rescue
    ''
  end
end

app/controllers/admin/videos_controller.rb
#encoding: utf-8
class Admin::VideosController < AdminController

 def index
    @videos = Video.in_title(params[:title])
                   .in_body(params[:body])
                   .in_owner(params[:owner_name])
                   .in_author(params[:author])
                   .in_remix(params[:remix])
                   .in_open(params[:open])
                   .in_main(params[:main])
                   .in_copyright(params[:copyright])
                   .order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    if @video.save
      redirect_to [:admin, @video]
    else
      render 'new'
    end
  end

  def edit
    @video = Video.find(params[:id])
    @video.copyright_extra = @video.copyright
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      redirect_to [:admin, @video]
    else
      render 'edit'
    end
  end

  def show
    @video = Video.find(params[:id])
    @author_videos = Video.where(user_id: @video.user_id).where(is_open: true)
    @friendly_videos = @video.friendly_videos
    @activities = UserActivity.where(content_id: @video.id)
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to [:admin, :videos]
  end

  def toggle_main
    @video = Video.find(params[:video_id])
    @video.main = !@video.main
    @video.save
    respond_to do |format|
      format.html
      format.js
    end
  end

  def toggle_open
    @video = Video.find(params[:video_id])
    @video.is_open = !@video.is_open
    @video.save
    respond_to do |format|
      format.html
      format.js
    end
  end

  def remote_videos
    @videos = Video.remote_videos(page: params[:page])
    @page = params[:page] || 1
  end

  def fetch_remote_video
    video_id = params[:remote_video_uri].split('/').last
    @video = Video.create_from_remote(video_id, current_user.id)
    if @video.persisted?
      redirect_to [:edit, :admin, @video]
    else
      redirect_to :back, alert: @video.errors.full_messages.join(", ")
    end
  end

  def fetch_selected_remote_videos
    remote_video_ids = params[:video_ids]
    remote_video_ids.each do |video_id|
      Video.create_from_remote(video_id, current_user.id)
    end
    render json: {redirect_url: admin_videos_path}
  end

  def video_params
    params.require(:video).permit(:title, :body, :link, :file, :recommend, :is_open, :main, :user_id, :tag_list, :owner_name, :owner_url, {:parent_content_ids => []}, :is_remix, :extra_copyright, :copyright_extra, :copyright)
  end
end

app/controllers/videos_controller.rb
#encoding: utf-8

class VideosController < ApplicationController

  def index
    @main_videos = Video.where(main: true).where(is_open: true).order("created_at DESC").limit(5)
    @videos = Video.where(is_open: true).page(params[:page]).order("created_at DESC").per(8)
  end

  def new
    @video = Video.new
    @video.is_remix = true
    authorize! :create, @video
  end

  def create
    @video = Video.new video_params
    @video.user = current_user
    if @video.save
      redirect_to root_url, notice: '비디오가 성공적으로 등록되었습니다. 관리자 승인 후 노출됩니다.'
    else
      render 'new'
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)
    if @video.save
      redirect_to @video
    else
      render 'edit'
    end
  end

  def show
    @video = Video.find(params[:id])
    @video.view = @video.view + 1
    @video.save

    @author_videos = Video.where(user_id: @video.user_id).where(is_open: true)
    @friendly_videos = @video.friendly_videos

    @warning = Warning.new
    @content = @video
  end

  def download
    @video = Video.find(params[:video_id])
    authorize! :download, @video
    @video.increase_download_count(current_user)
    redirect_to @video.download_url(params[:type_quality], params[:type_width])
  end

  def video_params
    params.require(:video).permit(:title, :body, :link, :file, :recommend, {:parent_content_ids => []}, :user_id, :tag_list, :is_remix, :owner_name, :owner_url, :extra_copyright, :copyright_extra, :copyright)
  end
end

app/views/videos/_form.html.haml
= bootstrap_form_for @video do |f|
  = f.text_field :title
  = f.text_area :body, rows: 10
  = f.text_field :link
  = f.check_box :is_remix
  = f.check_box :extra_copyright
  .basic_copyright_area
    = f.select :copyright, Content::COPYRIGHT
  .extra_copyright_area
    = f.text_field :copyright_extra
  = f.text_field :tag_list, placeholder: '콤마로 구별됩니다.'
  .parent-content-form
    = f.select :parent_content_ids, Content.all.map { |c| [c.title, c.id] }, {include_blank: true}, class: "chosen-select", :multiple => 'multiple'
  = f.text_field :owner_name
  = f.text_field :owner_url
  = f.submit

:javascript
  $(document).ready(function(){
    var check_parent_content_form = function() {
      var checked = $('#video_is_remix').is(":checked");
      if(checked){
        $('.parent-content-form').show();
      }else{
        $('.parent-content-form').hide();
      }
    };

    check_parent_content_form();
    $('#video_is_remix').click(function(e){
      check_parent_content_form();
    });
  });

app/views/videos/index.html.haml
.container
  .main_content_slide
    #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
      %ol.carousel-indicators
        - @main_videos.each_with_index do |main_video, index|
          %li{class: index == 0 ? 'active' : '', "data-slide-to" => index, "data-target" => "#carousel-example-generic"}
      .carousel-inner
        - @main_videos.each_with_index do |main_video, index|
          .item{ class: index == 0 ? 'active' : '' }
            = raw main_video.iframe_html
      %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
        %span &lt;
      %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
        %span &gt;

  .content-list-box
    .content-list-box__title
      최신 비디오
      = link_to '리믹스 업로드', [:new, :video], class: 'btn btn-default'

    .content-list-box__list.clearfix
      - @videos.each_slice(4) do |videos|
        %ul.unstyled
          - videos.each do |video|
            %li
              = link_to video do
                = image_tag video.thumbnail_url

    .clearfix

    .content-list-box__paginate.text-center
      = paginate @videos

app/views/videos/new.html.haml
.container
  %section
    .page-header
      %h2 비디오 리믹스 업로드
    = render 'form'

app/views/videos/show.html.haml
.background
- content_for :facebook_meta do
  = tag :meta, property: "og:type", content: "website"
  = tag :meta, property: "og:url", content: video_url(@video)
  = tag :meta, property: "og:title", content: "셀수스 - #{@video.title}"
  = tag :meta, property: "og:description", content: (@video.body)
.container
  %section
    .content-main
      .row
        .col-sm-7
          = raw @video.iframe_html
          .content-main__sns.text-left
            %a{"data-via" => "twitterdev", :href => "https://twitter.com/share"}
              = image_tag 'btn-tw.png', alt: "트위터버튼"
            %a{:href => "http://www.facebook.com/sharer.php?u=#{video_url(@video)}"}
              = image_tag 'btn-fb.png', alt: "페이스북버튼"
            %a{:href => "https://plus.google.com/share?url=#{video_url(@video)}"}
              = image_tag 'btn-google.png', alt: "구글버튼"
            .fb-like{"data-action" => "like", "data-href" => video_url(@video), "data-layout" => "button", "data-share" => "false", "data-show-faces" => "false"}
        .col-sm-5
          .content-main__spec.content-spec
            .content-spec__title
              = image_tag 'icon-video.png'
              %h3.iblc #{@video.title}
            %p.content-spec__text
              #{@video.body}
            %p.content-spec__text
              - if @video.owner_name
                저작권자 : #{@video.owner_name}
                (
                = link_to @video.check_owner_url, @video.check_owner_url
                )

            - if current_user
              = link_to '#', class: 'content-spec__link', "data-target" => "#warning", "data-toggle" => "modal" do
                저작권 신고하기
                = image_tag 'icon-button.png'
            - else
              = link_to '#', data: { confirm: '로그인 후 이용가능 합니다.'}, class: 'content-spec__link' do
                저작권 신고하기
                = image_tag 'icon-button.png'
            .content-spec__copyright
              - if @video.extra_copyright
                = link_to (@video.copy_right_image_url), @video.copy_right_licence_info_url
              - else
                = link_to image_tag(@video.copy_right_image_url), @video.copy_right_licence_info_url
          .content-main__download.content-download
            %ul.content-download__list
              - if @video.download_links_hash.present?
                - @video.download_links_hash.each do |down|
                  %li.content-size{"data-download-url" => video_download_path(@video, type_quality: down["quality"], type_width: down["width"])}
                    %input.content-size__radio{:type => "radio", name: "video_radio", value: down["quality"]}
                    %span.content-size__option
                      = "#{down['width']} X #{down['height']}"
                    %span.content-size__type
                      = down["type"]
                .content-download__button.text-center{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
                  %a{:href => "#", :role => "button", :class => "iblc", id: 'video-quality-check'} 다운로드
              - else
                .text-center
                  %br
                  = '다운로드를 제공하지 않습니다.'

    .content
      .content-box
        %h4.content-box__title
          ="키워드"
        %p.content-box__description
          - if @video.tags
            - @video.tags.each do |tag|
              %span.label.label-default
                = link_to tag.name, [:tags, :contents, tag: tag.name]

      - if @friendly_videos.present?
        .content-box
          %h4.content-box__title
            ="관련 비디오"
          .content-box__imglist.content-imglist
            .img-list.als-container
              %span.als-prev
                = image_tag 'icon-arrow-left.png', alt: '왼쪽버튼'
              .als-viewport
                %ul.als-wrapper
                  - @friendly_videos.each do |fr_video|
                    %li.als-item
                      = link_to image_tag(fr_video.thumbnail_url), fr_video
              %span.als-next
                = image_tag 'icon-arrow-right.png', alt: '오른쪽버튼'
            .clearfix
      - if request.referer =~/remix/
        = render '/contents/recent_remix'
      - elsif @author_videos.present?
        .content-box
          %h4.content-box__title
            ="작가의 최신 비디오"
          .content-box__imglist.content-imglist
            .img-list.als-container
              %span.als-prev
                = image_tag 'icon-arrow-left.png', alt: '왼쪽버튼'
              .als-viewport
                %ul.als-wrapper
                  - @author_videos.each do |author_video|
                    %li.als-item
                      = link_to image_tag(author_video.thumbnail_url), author_video
              %span.als-next
                = image_tag 'icon-arrow-right.png', alt: '오른쪽버튼'
            .clearfix

  %section
    .fb-comments{"data-colorscheme" => "light", "data-href" => video_url(@video), "data-numposts" => "5", "width" => "100%" , "data-width" => "100%"}
  .text-center
    = link_to '목록으로', [:videos], class: 'btn btn-default'


  = render 'warning_modal'
  = render 'social_share_script'
  = render 'download_modal', content: @video

:javascript
  $(function() {
    $(".content-download").on("click", ".content-size", function(e) {
      var $wrapper = $(e.delegateTarget);
      var url = $(this).data("download-url");
      $(this).find('.content-size__radio').prop('checked', true);
      $("#content-download-btn").attr("href", url);
    });

    $("#video-quality-check").on("click", function(e){
      var checked = false;
      var obj = $(".content-size__radio");
      $.each( obj, function( key, value ) {
        if(value.checked){ checked = true; }
      });

      if(!checked){
        alert("비디오 옵션을 선택해주세요.");
        e.stopPropagation();
      }
    });
  });