config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :redactor do
    resources :pictures, :only => [:index, :create]
  end

  unless Rails.env.production?
    get "master_login" => "pages#master_login"
  end

  root 'pages#home'
  get 'pages/temporary' => 'pages#temporary'

  resources :contents do
    get 'search', on: :collection
    get 'tags', on: :collection
  end

  resources :videos do
    get 'download'
  end
  resources :audios do
    get 'download'
  end
  resources :images do
    get 'download'
  end
  resources :remixes do
    get 'download'
  end
  resources :warnings
  resources :posts

  resources :pages do
    post :change_user_session
  end

  namespace :admin do
    resources :users
    resources :user_activities
    resources :posts
    resources :warnings
    resources :videos  do
      put 'toggle_main'
      put 'toggle_open'
      get 'remote_videos', on: :collection
      post 'fetch_selected_remote_videos', on: :collection
      post 'fetch_remote_video', on: :collection
    end
    resources :audios  do
      get 'remote_audios', on: :collection
      post 'fetch_selected_remote_audios', on: :collection
      post 'fetch_remote_audio', on: :collection
      put 'toggle_main'
      put 'toggle_open'
    end
    resources :images  do
      get 'remote_images', on: :collection
      post 'fetch_selected_remote_images', on: :collection
      post 'fetch_remote_image', on: :collection
      put 'toggle_main'
      put 'toggle_open'
    end
    resources :contents
    resources :categories
    root 'videos#index'
  end

end

app/models/image.rb
#encoding: utf-8
class Image < Content
  before_validation :adjust_remote_content_id
  before_validation :fetch_image_info
  validate :check_duplicate

  mount_uploader :file, ImageUploader

  def self.remote_images
    ## 문서: https://docs.google.com/document/d/16M3qaw27vgwuwXqExo0aIC0nni42OOuWu_OGvpYl7dE/pub#h.cibfsb83bh1n
    ## public으로 설정된 것만 나옴.
    resp = RestClient.get("https://api.imageshack.com/v2/user/celsuscoop/images")
    hash = JSON.parse(resp)
    images_data = hash["result"]["images"]
    result = images_data.map do |image_data|
      if Image.where(remote_content_id: image_data["id"]).blank?
        RemoteImage.new(image_data)
      end
    end.compact
  end

  def friendly_images
    friendly_images = []
    self.tag_list.each do |tag|
      friendly_images << Image.where(is_open: true).tagged_with(tag)
    end
    friendly_images.flatten.uniq - [self]
  end

  def adjust_remote_content_id
    if self.link.present? && link_changed?
      self.remote_content_id = self.link.split("/").last
    end
  end

  def check_duplicate
    if self.file.present? && self.link.present?
      errors.add(:link, "하나만 올려야 합니다.")
      errors.add(:file, "하나만 올려야 합니다.")
    end
  end

  def download_url
    self.iframe_html
  end

  def iframe_html
    if file.present?
      file.url
    else
      read_attribute(:iframe_html)
    end
  end

  def self.popular
    # FIXME:  view + download_count 로 로직 수정 필요
    order('view ASC').limit(18)
  end

  def thumbnail_url
    if self.file.present?
      self.file.url(:thumb)
    else
      resized_remote_url(240, 135)
    end
  end

  def middle_size_url
    if self.file.present?
      self.file.url(:middle)
    else
      resized_remote_url(575, 381)
    end
  end

  def large_size_url
    if self.file.present?
      self.file.url(:large)
    else
      resized_remote_url(1006, 400)
    end
  end

  def resized_remote_url(width, height)
    server = self.source_info["result"]["server"]
    filename = self.source_info["result"]["filename"]
    thumbnail = "https://imagizer.imageshack.us/#{width}x#{height}/#{server}/#{filename}"
  end

  def self.create_from_remote(remote_content_id, user_id)
    image = Image.new(user_id: user_id, remote_content_id: remote_content_id)
    image.save
    image
  end

  private

  def fetch_image_info
    return if not remote_content_id_changed?
    if file.blank? && remote_content_id.present? && remote_content_id_changed?
      request_url = "https://api.imageshack.com/v2/images/#{self.remote_content_id}?api_key=#{ENV['IMAGE_SHAKER_API_KEY']}"
      resp_hash = _fetch_image_info(request_url)
      if resp_hash.present?
        self.title = resp_hash["result"]["filename"] if self.title.blank?
        self.link  = "https://imageshack.com/i/#{resp_hash['result']['id']}" if self.link.blank?
        self.source_info = resp_hash
        self.iframe_html = 'http://' + resp_hash["result"]["direct_link"]
      else
        errors.add(:link, "이미지를 가져올 수 없습니다. 주소를 다시 한번 확인해 주세요.")
      end
    end
  end

  def _fetch_image_info(request_url)
    resp =  RestClient.get(request_url)
    JSON.parse(resp)
  rescue
    {}
  end
end

app/controllers/admin/images_controller.rb
#encoding: utf-8
class Admin::ImagesController < AdminController
  def index
    @images = Image.in_title(params[:title])
                    .in_body(params[:body])
                    .in_owner(params[:owner_name])
                    .in_author(params[:author])
                    .in_remix(params[:remix])
                    .in_open(params[:open])
                    .in_main(params[:main])
                    .in_copyright(params[:copyright])
                    .order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user = current_user
    if @image.save
      redirect_to [:admin, @image]
    else
      render 'new'
    end
  end

  def edit
    @image = Image.find(params[:id])
    @image.copyright_extra = @image.copyright
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to [:admin, @image]
    else
      render 'edit'
    end
  end

  def show
    @image = Image.find(params[:id])
    @author_images = Image.where(user_id: @image.user_id).where(is_open: true)
    @friendly_images = @image.friendly_images
    @activities = UserActivity.where(content_id: @image.id)
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to [:admin, :images]
  end

  def toggle_main
    @image = Image.find(params[:image_id])
    @image.main = !@image.main
    @image.save
    respond_to do |format|
      format.html
      format.js
    end
  end

  def toggle_open
    @image = Image.find(params[:image_id])
    @image.is_open = !@image.is_open
    @image.save
    respond_to do |format|
      format.html
      format.js
    end
  end

  def remote_images
    @images = Image.remote_images
  end

  def fetch_remote_image
    image_id = params[:image_id]
    @image = Image.create_from_remote(image_id, current_user.id)
    if @image.persisted?
      redirect_to [:edit, :admin, @image]
    else
      redirect_to :back, alert: @image.errors.full_messages.join(", ")
    end
  end

  def fetch_selected_remote_images
    remote_image_ids = params[:image_ids]
    remote_image_ids.each do |image_id|
      Image.create_from_remote(image_id, current_user.id)
    end
    render json: {redirect_url: admin_images_path}
  end

  def image_params
    params.require(:image).permit(:title, :body, :link, :file, :recommend, :is_open, :main, {:parent_content_ids => []}, :user_id, :tag_list, :owner_name, :owner_url, :is_remix, :extra_copyright, :copyright_extra, :copyright, :author, :remix, :open)
  end
end

app/controllers/images_controller.rb
#encoding: utf-8

class ImagesController < ApplicationController

  def index
    @main_images = Image.where(main: true).where(is_open: true).order("created_at DESC").limit(5)
    @images = Image.where(is_open: true).order("created_at DESC").page(params[:page]).per(8)
  end

  def new
    @image = Image.new
    @image.is_remix = true
    authorize! :create, @image

  end

  def create
    @image = Image.new image_params
    @image.user = current_user
    if @image.save
      redirect_to root_url, notice: '이미지가 성공적으로 등록되었습니다. 관리자 승인 후 노출됩니다.'
    else
      render 'new'
    end
  end

  def show
    @image = Image.find(params[:id])
    @image.view = @image.view + 1
    @image.save

    @author_images = Image.where(user_id: @image.user_id).where(is_open: true)
    @friendly_images = @image.friendly_images

    @warning = Warning.new
    @content = @image
  end

  def download
    @image = Image.find(params[:image_id])
    authorize! :download, @image
    @image.increase_download_count(current_user)
    redirect_to @image.download_url
  end
  def image_params
    params.require(:image).permit(:title, :body, :link, :file, :recommend, {:parent_content_ids => []}, :user_id, :tag_list, :is_remix, :owner_name, :owner_url, :extra_copyright, :copyright_extra, :copyright)
  end
end

app/views/admin/images/_form.html.haml
= bootstrap_form_for [:admin, @image] do |f|
  = f.text_field :title
  = f.text_area :body, rows: 10
  = f.text_field :link
  = f.file_field :file
  = f.check_box :extra_copyright
  .basic_copyright_area
    = f.select :copyright, Content::COPYRIGHT
  .extra_copyright_area
    = f.text_field :copyright_extra
  = f.check_box :is_remix
  = f.text_field :tag_list
  .parent-content-form
    = f.select :parent_content_ids, Content.all.map { |c| [c.title, c.id] }, {include_blank: true}, class: "chosen-select", :multiple => 'multiple'
  = f.text_field :owner_name
  = f.text_field :owner_url
  = f.submit

:javascript
  $(document).ready(function(){
    var check_parent_content_form = function() {
      var checked = $('#image_is_remix').is(":checked");
      if(checked){
        $('.parent-content-form').show();
      }else{
        $('.parent-content-form').hide();
      }
    };

    check_parent_content_form();
    $('#image_is_remix').click(function(e){
      check_parent_content_form();
    });
  });

app/views/admin/images/edit.html.haml
%section
  .page-header
    %h2 EDIT
  = render 'form'

app/views/admin/images/index.html.haml
%section
  .page-header
    %h2 이미지

  .well.admin-content-list-box
    .admin-content-search.text-center
      = form_tag([:admin, :images], method: "get") do
        - content_copyright = Content.pluck(:copyright).uniq
        .admin-search-wrapper
          .row
            .col-xs-1
              = label_tag "작성자"
            .col-xs-2
              = text_field_tag(:author, value=nil, options = {:value => params[:author], class: 'form-control content-search__form iblc'})
            .col-xs-1
              = label_tag "제목"
            .col-xs-2
              = text_field_tag(:title, value=nil, options = {:value => params[:title], class: 'form-control content-search__form iblc'})
            .col-xs-1
              = label_tag "본문"
            .col-xs-2
              = text_field_tag(:body, value=nil, options = {:value => params[:body], class: 'form-control content-search__form iblc'})
            .col-xs-1
              = label_tag "권리자"
            .col-xs-2
              = text_field_tag(:owner_name, value=nil, options = {:value => params[:owner_name], class: 'form-control content-search__form iblc'})
          .row
            .col-xs-1
              = label_tag "리믹스"
            .col-xs-2
              = select_tag 'remix', options_for_select([['리믹스', true], ['리믹스아님',false]], (params[:remix] rescue '')), class: "selectpicker iblc", :prompt => "---------"
            .col-xs-1
              = label_tag "공개"
            .col-xs-2.text-left
              = select_tag 'open', options_for_select([['공개', true], ['비공개',false]], (params[:open] rescue '')), class: "selectpicker iblc", :prompt => "---------"
            .col-xs-1
              = label_tag "메인노출"
            .col-xs-2.text-left
              = select_tag 'main', options_for_select([['노출', true], ['노출 안함',false]], (params[:main] rescue '')), class: "selectpicker iblc", :prompt => "---------"
            .col-xs-1
              = label_tag "저작권"
            .col-xs-2
              = select_tag 'copyright', options_for_select(content_copyright, (params[:copyright] rescue '')), class: "selectpicker iblc", :prompt => "저작권을 선택해 주세요"
          .row
            .col-xs-11.text-right
              = submit_tag "검색", class: 'btn btn-purple search-bar__submit_btn iblc'

%div
  = link_to "등록", [:new, :admin, :image], class: 'btn btn-default'
  = link_to "리모트", [:remote_images, :admin, :images], class: 'btn btn-default'

%table.table.table
  %thead
    %tr
      %th
        %label 썸네일
      %th
        %label 제목
      %th
        %label 리믹스
      %th
        %label 공개
      %th
        %label 메인노출
      %th
        %label 작성자
      %th
  %tbody
    - page = params[:page] || '1'
    - @images.each do |image|
      %tr
        %td
          .thumb{ style: "background-image: url(#{image.thumbnail_url}); height: 100px; width: 150px;"}
        %td
          = link_to image.title, [:admin, image]
        %td
          = image.remix_ko
        %td.is_open_td[image]
          %p= image.is_open
          = link_to '변경', [:admin , image, :toggle_open, page: page], method: :put, class: 'btn btn-xs btn-default', :remote => true if can? :toggle_open, image
        %td.main_td[image]
          %p= image.main
          = link_to '변경', [:admin , image, :toggle_main, page: page], method: :put, class: 'btn btn-xs btn-default', :remote => true if can? :toggle_main, image
        %td
          = image.user.name if image.user
        %td
          = link_to '수정', [:edit, :admin, image], class: 'btn btn-xs btn-default'  if can? :update, image
.paginate
  = paginate @images

app/views/admin/images/new.html.haml
.container
  %section
    .page-header
      %h2 이미지 업로드
    = render 'form'

app/views/admin/images/remote_images.html.haml
- if @images.present?
  %table.table
    %tr
      %th= check_box_tag :check_all
      %th 이미지
      %th 제목
      %th 저작권
      %th
    - @images.each do |image|
      %tr
        %td= check_box_tag "image[id][]", image.id, false, class: "image_row", id: nil
        %td= image_tag image.thumbnail_url, style: "width: 200px;"
        %td= image.name
        %td= image.license_ko
        %td= link_to '가져오기', fetch_remote_image_admin_images_path(image_id: image.id), class: 'btn btn-default btn-sm', method: 'post'
    = link_to '선택가져오기', fetch_selected_remote_images_admin_images_path, class: 'btn btn-default btn-sm fetch_images'

- else
  = '새로운 이미지가 없습니다.'

:javascript
  $(function() {
    $("#check_all").click(function() {
      var is_checked = $(this).is(":checked");
      $(".image_row").prop('checked', is_checked);
    });

    $(".fetch_images").click(function(e) {
      e.preventDefault();
      var selected_image_ids = [];
      $.each( $('.image_row:checked'), function(i, obj) {
        selected_image_ids.push($(obj).val());
      });
      var url = $(this).attr("href");

      var csrf_token = $('meta[name=csrf-token]').attr('content');
      var csrf_param = $('meta[name=csrf-param]').attr('content');
      var params = {};
      params[csrf_param] = csrf_token;
      params['image_ids']  = selected_image_ids;
      $.post( url, params, function(data) {
        window.location = data.redirect_url;
      });
    });
  });

app/views/admin/images/show.html.haml
.container
  %section
    .content-main
      .row
        .col-sm-7
          = image_tag @image.iframe_html
        .col-sm-5
          .content-main__spec.content-spec
            .content-spec__title
              = image_tag 'icon-video.png'
              %h3.iblc 제목 : #{@image.title}
            %p.content-spec__text
              내용 : #{@image.body}
            %p.content-spec__text
              = @image.link
            %p.content-spec__text
              - if @image.owner_name
                권리자 : #{@image.owner_name}
                (
                = link_to @image.check_owner_url, @image.check_owner_url
                )
            .content-spec__copyright
              - if @image.extra_copyright
                = link_to (@image.copy_right_image_url), @image.copy_right_licence_info_url
              - else
                = link_to image_tag(@image.copy_right_image_url), @image.copy_right_licence_info_url
          .content-main__download.content-download
            .content-download__button.text-center
              %a{:href => @image.download_url, :role => "button", :class => "iblc"} 다운로드
    .content
      .content-box
        %h4.content-box__title
          ="키워드"
        %p.content-box__description
          - if @image.tags
            - @image.tags.each do |tag|
              %span.label.label-default
                = link_to tag.name, [:tags, :contents, tag: tag.name]

      - if @friendly_images.present?
        .content-box
          %h4.content-box__title
            ="관련 이미지"
          .content-box__imglist.content-imglist
            .img-list.als-container
              %span.als-prev
                = image_tag 'icon-arrow-left.png', alt: '왼쪽버튼'
              .als-viewport
                %ul.als-wrapper
                  - @friendly_images.each do |fr_image|
                    %li.als-item
                      = link_to image_tag(fr_image.thumbnail_url), fr_image
              %span.als-next
                = image_tag 'icon-arrow-right.png', alt: '오른쪽버튼'
            .clearfix
      - if @author_images.present?
        .content-box
          %h4.content-box__title
            ="작가의 최신 이미지"
          .content-box__imglist.content-imglist
            .img-list.als-container
              %span.als-prev
                = image_tag 'icon-arrow-left.png', alt: '왼쪽버튼'
              .als-viewport
                %ul.als-wrapper
                  - @author_images.each do |author_image|
                    %li.als-item
                      = link_to image_tag(author_image.thumbnail_url), author_image
              %span.als-next
                = image_tag 'icon-arrow-right.png', alt: '오른쪽버튼'
            .clearfix
      - if current_user.admin?
        .content-box.content-activity
          %h4.content-box__title
            다운로드 정보
          %p= "다운로드 횟수 : #{@activities.count}회"
          %p= link_to "이 컨텐츠의 다운로드 현황 보러가기", [:admin, :user_activities, content_id: @image.id]
        .clearfix
  .text-center
    = link_to '목록으로', [:admin, :images], class: 'btn btn-default'
    = link_to '수정하기', [:edit, :admin, @image], class: 'btn btn-default' if can? :update, @image
    = link_to '삭제하기', [:admin, @image], method: 'delete', data: {  confirm: '정말 삭제하시겠습니까?' }, class: 'btn btn-default'  if can? :destroy, @image

  :javascript
    $(function() {
      $(".content-download").on("change", "input.content-size__radio", function(e) {
        var $wrapper = $(e.delegateTarget);
        var url = $(this).parent("li.content-size").data("download-url");
        $wrapper.find('.content-download__button a').attr("href", url);
      });
    });

app/views/admin/images/toggle_main.js.erb
if (<%= @image.main %> == true){
  $('.main_td#image_<%= @image.id %>').find('p').html('<p>true</p>');
} else if (<%= @image.main %> == false){
  $('.main_td#image_<%= @image.id %>').find('p').html('<p>false</p>');
}

app/views/admin/images/toggle_open.js.erb
if (<%= @image.is_open %> == true){
  $('.is_open_td#image_<%= @image.id %>').find('p').html('<p>true</p>');
} else if (<%= @image.is_open %> == false){
  $('.is_open_td#image_<%= @image.id %>').find('p').html('<p>false</p>');
}