config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :redactor do
    resources :pictures, :only => [:index, :create]
  end

  unless Rails.env.production?
    get "master_login" => "pages#master_login"
  end

  root 'pages#home'
  get 'pages/temporary' => 'pages#temporary'

  resources :contents do
    get 'search', on: :collection
    get 'tags', on: :collection
  end

  resources :videos do
    get 'download'
  end
  resources :audios do
    get 'download'
  end
  resources :images do
    get 'download'
  end
  resources :remixes do
    get 'download'
  end
  resources :warnings
  resources :posts

  resources :pages do
    post :change_user_session
  end

  namespace :admin do
    resources :users
    resources :user_activities
    resources :posts
    resources :warnings
    resources :videos  do
      put 'toggle_main'
      put 'toggle_open'
      get 'remote_videos', on: :collection
      post 'fetch_selected_remote_videos', on: :collection
      post 'fetch_remote_video', on: :collection
    end
    resources :audios  do
      get 'remote_audios', on: :collection
      post 'fetch_selected_remote_audios', on: :collection
      post 'fetch_remote_audio', on: :collection
      put 'toggle_main'
      put 'toggle_open'
    end
    resources :images  do
      get 'remote_images', on: :collection
      post 'fetch_selected_remote_images', on: :collection
      post 'fetch_remote_image', on: :collection
      put 'toggle_main'
      put 'toggle_open'
    end
    resources :contents
    resources :categories
    root 'videos#index'
  end

end

app/models/video.rb
#encoding: utf-8
class Video < Content
  before_validation :adjust_remote_content_id
  before_validation :fetch_video_info

  validates :remote_content_id, :user_id, presence: true
  validate :unique_remote_content_id
  validate :source_info_fetched

  def self.popular
    # FIXME:  view + download_count 로 로직 수정 필요
    order('view ASC').limit(18)
  end

  def self.remote_videos(page: nil, per_page: nil)
    _page = page.presence || 1
    _per_page = per_page.presence || 20
    resp = RestClient.get("https://api.vimeo.com/me/videos?page=#{_page}&per_page=#{_per_page}", {"Authorization" => "bearer #{ENV['VIMEO_ACCESS_TOKEN']}"})
    hash = JSON.parse(resp)
    hash["data"].map do |video_data|
      video_data_id = video_data["uri"].split("/").last
      r_video = RemoteVideo.new(video_data)
      if Video.where(remote_content_id: video_data_id).present?
        r_video.already_taken = true
      end
      r_video
    end.compact
  rescue RestClient::BadRequest => e
    []
  end

  def self.create_from_remote(video_id, user_id)
    Video.create(user_id: user_id, remote_content_id: video_id)
  end

  def friendly_videos
    friendly_videos = []
    self.tag_list.each do |tag|
      friendly_videos << Video.where(is_open: true).tagged_with(tag)
    end
    friendly_videos.flatten.uniq - [self]
  end

  def license_match(license)
    _license = ''
    if(license.nil?)
      errors.add(:link, "저작권 승인이 안되는 컨텐츠 입니다.")
    elsif (license == 'by')
      _license = Content::COPYRIGHT[0]
    elsif (license == 'by-nc')
      _license = Content::COPYRIGHT[1]
    elsif (license == 'by-nd')
      _license = Content::COPYRIGHT[2]
    elsif (license == 'by-sa')
      _license = Content::COPYRIGHT[3]
    elsif (license == 'by-nc-sa')
      _license = Content::COPYRIGHT[4]
    elsif (license == 'by-nc-nd')
      _license = Content::COPYRIGHT[5]
    elsif (license == 'cc0')
      _license = Content::COPYRIGHT[6]
    end
    _license
  end

  def download_links_hash
    self.source_info["download"]
  end

  def download_url(type_quality, type_width)
    download_info = self.download_links_hash.select{|type| (type["quality"] == type_quality) && (type["width"] == type_width.to_i)}.first
    return if download_info.blank?

    expire_at = Time.parse(download_info["expires"])
    if expire_at < Time.now
      _set_video_info( _fetch_video_info )
      self.save
    end
    download_info = self.reload.download_links_hash.select{|type| type["quality"] == type_quality }.first
    download_info["link"]
  end

  def adjust_remote_content_id
    if link_changed?
      self.remote_content_id = self.link.split("/").last
    end
  end

  def fetch_video_info
    return if not remote_content_id_changed?
    resp_hash = _fetch_video_info
    return if resp_hash.blank?
    _set_video_info(resp_hash)
  end

  def unique_remote_content_id
    video = Video.where(remote_content_id: self.remote_content_id).last
    if video.present? && video.id != self.id
      errors.add(:link, "이미 존재하는 비디오 입니다.")
    end
  end

  def source_info_fetched
    if source_info.blank?
      errors.add(:link, '잘못된 주소이거나, 비디오 정보를 가져오는데 실패했습니다.')
    end
  end

  def _fetch_video_info
    request_url =  "https://api.vimeo.com/videos/#{self.remote_content_id}"
    resp = RestClient.get(request_url, {"Authorization" => "bearer #{ENV['VIMEO_ACCESS_TOKEN']}"} )
    JSON.parse(resp)
  rescue
    {}
  end

  def _set_video_info(resp_hash)
    self.source_info = resp_hash
    string = <<-RUBY
<iframe width="100%" height="400" scrolling="no" frameborder="no" src="//player.vimeo.com/video/#{self.remote_content_id}"></iframe>
RUBY
    self.iframe_html = string
    self.title = self.source_info["name"] if self.title.blank?
    _copyright = license_match(source_info["license"])
    self.copyright = _copyright if self.copyright.blank?
    self.link = self.source_info["link"]
  end

  def thumbnail_url
    source_info['pictures'].select {|p| p['width'] == 295 }.first["link"]
  rescue
    ''
  end
end

app/controllers/admin/videos_controller.rb
#encoding: utf-8
class Admin::VideosController < AdminController

 def index
    @videos = Video.in_title(params[:title])
                   .in_body(params[:body])
                   .in_owner(params[:owner_name])
                   .in_author(params[:author])
                   .in_remix(params[:remix])
                   .in_open(params[:open])
                   .in_main(params[:main])
                   .in_copyright(params[:copyright])
                   .order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    if @video.save
      redirect_to [:admin, @video]
    else
      render 'new'
    end
  end

  def edit
    @video = Video.find(params[:id])
    @video.copyright_extra = @video.copyright
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      redirect_to [:admin, @video]
    else
      render 'edit'
    end
  end

  def show
    @video = Video.find(params[:id])
    @author_videos = Video.where(user_id: @video.user_id).where(is_open: true)
    @friendly_videos = @video.friendly_videos
    @activities = UserActivity.where(content_id: @video.id)
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to [:admin, :videos]
  end

  def toggle_main
    @video = Video.find(params[:video_id])
    @video.main = !@video.main
    @video.save
    respond_to do |format|
      format.html
      format.js
    end
  end

  def toggle_open
    @video = Video.find(params[:video_id])
    @video.is_open = !@video.is_open
    @video.save
    respond_to do |format|
      format.html
      format.js
    end
  end

  def remote_videos
    @videos = Video.remote_videos(page: params[:page])
    @page = params[:page] || 1
  end

  def fetch_remote_video
    video_id = params[:remote_video_uri].split('/').last
    @video = Video.create_from_remote(video_id, current_user.id)
    if @video.persisted?
      redirect_to [:edit, :admin, @video]
    else
      redirect_to :back, alert: @video.errors.full_messages.join(", ")
    end
  end

  def fetch_selected_remote_videos
    remote_video_ids = params[:video_ids]
    remote_video_ids.each do |video_id|
      Video.create_from_remote(video_id, current_user.id)
    end
    render json: {redirect_url: admin_videos_path}
  end

  def video_params
    params.require(:video).permit(:title, :body, :link, :file, :recommend, :is_open, :main, :user_id, :tag_list, :owner_name, :owner_url, {:parent_content_ids => []}, :is_remix, :extra_copyright, :copyright_extra, :copyright)
  end
end

app/controllers/videos_controller.rb
#encoding: utf-8

class VideosController < ApplicationController

  def index
    @main_videos = Video.where(main: true).where(is_open: true).order("created_at DESC").limit(5)
    @videos = Video.where(is_open: true).page(params[:page]).order("created_at DESC").per(8)
  end

  def new
    @video = Video.new
    @video.is_remix = true
    authorize! :create, @video
  end

  def create
    @video = Video.new video_params
    @video.user = current_user
    if @video.save
      redirect_to root_url, notice: '비디오가 성공적으로 등록되었습니다. 관리자 승인 후 노출됩니다.'
    else
      render 'new'
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)
    if @video.save
      redirect_to @video
    else
      render 'edit'
    end
  end

  def show
    @video = Video.find(params[:id])
    @video.view = @video.view + 1
    @video.save

    @author_videos = Video.where(user_id: @video.user_id).where(is_open: true)
    @friendly_videos = @video.friendly_videos

    @warning = Warning.new
    @content = @video
  end

  def download
    @video = Video.find(params[:video_id])
    authorize! :download, @video
    @video.increase_download_count(current_user)
    redirect_to @video.download_url(params[:type_quality], params[:type_width])
  end

  def video_params
    params.require(:video).permit(:title, :body, :link, :file, :recommend, {:parent_content_ids => []}, :user_id, :tag_list, :is_remix, :owner_name, :owner_url, :extra_copyright, :copyright_extra, :copyright)
  end
end

app/views/admin/videos/_form.html.haml
= bootstrap_form_for [:admin, @video] do |f|
  = f.text_field :title
  = f.text_area :body, rows: 10
  = f.text_field :link
  = f.check_box :is_remix
  = f.check_box :extra_copyright
  .basic_copyright_area
    = f.select :copyright, Content::COPYRIGHT
  .extra_copyright_area
    = f.text_field :copyright_extra
  = f.text_field :tag_list, placeholder: '콤마로 구별됩니다.'
  .parent-content-form
    = f.select :parent_content_ids, Content.all.map { |c| [c.title, c.id] }, {include_blank: true}, class: "chosen-select", :multiple => 'multiple'
  = f.text_field :owner_name
  = f.text_field :owner_url
  = f.submit

:javascript
  $(document).ready(function(){
    var check_parent_content_form = function() {
      var checked = $('#video_is_remix').is(":checked");
      if(checked){
        $('.parent-content-form').show();
      }else{
        $('.parent-content-form').hide();
      }
    };

    check_parent_content_form();
    $('#video_is_remix').click(function(e){
      check_parent_content_form();
    });
  });

app/views/admin/videos/edit.html.haml
%section
  .page-header
    %h2 EDIT
  = render 'form'

app/views/admin/videos/index.html.haml
%section
  .page-header
    %h2 비디오

  .well.admin-content-list-box
    .admin-content-search.text-center
      = form_tag([:admin, :videos], method: "get") do
        - content_copyright = Content.pluck(:copyright).uniq
        .admin-search-wrapper
          .row
            .col-xs-1
              = label_tag "작성자"
            .col-xs-2
              = text_field_tag(:author, value=nil, options = {:value => params[:author], class: 'form-control content-search__form iblc'})
            .col-xs-1
              = label_tag "제목"
            .col-xs-2
              = text_field_tag(:title, value=nil, options = {:value => params[:title], class: 'form-control content-search__form iblc'})
            .col-xs-1
              = label_tag "본문"
            .col-xs-2
              = text_field_tag(:body, value=nil, options = {:value => params[:body], class: 'form-control content-search__form iblc'})
            .col-xs-1
              = label_tag "권리자"
            .col-xs-2
              = text_field_tag(:owner_name, value=nil, options = {:value => params[:owner_name], class: 'form-control content-search__form iblc'})
          .row
            .col-xs-1
              = label_tag "리믹스"
            .col-xs-2
              = select_tag 'remix', options_for_select([['리믹스', true], ['리믹스아님',false]], (params[:remix] rescue '')), class: "selectpicker iblc", :prompt => "---------"
            .col-xs-1
              = label_tag "공개"
            .col-xs-2.text-left
              = select_tag 'open', options_for_select([['공개', true], ['비공개',false]], (params[:open] rescue '')), class: "selectpicker iblc", :prompt => "---------"
            .col-xs-1
              = label_tag "메인노출"
            .col-xs-2.text-left
              = select_tag 'main', options_for_select([['노출', true], ['노출 안함',false]], (params[:main] rescue '')), class: "selectpicker iblc", :prompt => "---------"
            .col-xs-1
              = label_tag "저작권"
            .col-xs-2
              = select_tag 'copyright', options_for_select(content_copyright, (params[:copyright] rescue '')), class: "selectpicker iblc", :prompt => "저작권을 선택해 주세요"
          .row
            .col-xs-11.text-right
              = submit_tag "검색", class: 'btn btn-purple search-bar__submit_btn iblc'
= link_to "등록", [:new, :admin, :video], class: 'btn btn-default'
= link_to "리모트", [:remote_videos, :admin, :videos], class: 'btn btn-default'
%table.table.table
  %thead
    %tr
      %th
        %label 썸네일
      %th
        %label 제목
      %th
        %label 리믹스
      %th
        %label 공개
      %th
        %label 메인노출
      %th
        %label 작성자
      %th
  %tbody
    - page = params[:page] || '1'
    - @videos.each do |video|
      %tr
        %td
          = image_tag video.thumbnail_url
        %td
          = link_to video.title, [:admin, video]
        %td
          = video.remix_ko
        %td.is_open_td[video]
          %p= video.is_open
          = link_to '변경', [:admin , video, :toggle_open, page: page], method: :put, class: 'btn btn-xs btn-default', :remote => true if can? :toggle_open, video
        %td.main_td[video]
          %p= video.main
          = link_to '변경', [:admin , video, :toggle_main, page: page], method: :put, class: 'btn btn-xs btn-default', :remote => true if can? :toggle_main, video
        %td
          = video.user.name if video.user
        %td
          = link_to '수정', [:edit, :admin, video], class: 'btn btn-xs btn-default' if can? :update, video
.paginate
  = paginate @videos

app/views/admin/videos/new.html.haml
.container
  %section
    .page-header
      %h2 비디오 업로드
    = render 'form'

app/views/admin/videos/remote_videos.html.haml
- if @videos.present?
  %table.table
    %tr
      %th= check_box_tag :check_all
      %th 비디오
      %th 제목
      %th 저작권
      %th
    - @videos.each do |video|
      %tr
        %td
          - unless video.already_taken?
            = check_box_tag "video[id][]", video.link.split('/').last, false, class: "video_row", id: nil
        %td= image_tag video.thumbnail_url, style: "width: 200px;"
        %td= video.name
        %td= video.license_ko
        %td
          - if video.already_taken?
            = '이미 가져온 비디오 입니다'
          - else
            = link_to '가져오기', fetch_remote_video_admin_videos_path(remote_video_uri: video.uri), class: 'btn btn-default btn-sm', method: 'post' if video.license.present?
    = link_to '선택가져오기', fetch_selected_remote_videos_admin_videos_path, class: 'btn btn-default btn-sm fetch_videos'

- else
  = '새로운 비디오가 없습니다.'

.pagination
  - if @page != 1
    = link_to '이전', remote_videos_admin_videos_path(page: @page.to_i - 1), class: 'btn btn-default', style: 'margin-right: 50px;'
  - if @videos.present?
    = link_to '다음', remote_videos_admin_videos_path(page: @page.to_i + 1), class: 'btn btn-default'

:javascript
  $(function() {
    $("#check_all").click(function() {
      var is_checked = $(this).is(":checked");
      $(".video_row").prop('checked', is_checked);
    });

    $(".fetch_videos").click(function(e) {
      e.preventDefault();
      var selected_video_ids = [];
      $.each( $('.video_row:checked'), function(i, obj) {
        selected_video_ids.push($(obj).val());
      });
      var url = $(this).attr("href");
      var csrf_token = $('meta[name=csrf-token]').attr('content');
      var csrf_param = $('meta[name=csrf-param]').attr('content');
      var params = {};
      params[csrf_param] = csrf_token;
      params['video_ids']  = selected_video_ids;
      $.post( url, params, function(data) {
        window.location = data.redirect_url;
      });
    });
  });

app/views/admin/videos/show.html.haml
.container
  %section
    .content-main
      .row
        .col-sm-7
          = raw @video.iframe_html
        .col-sm-5
          .content-main__spec.content-spec
            .content-spec__title
              = image_tag 'icon-video.png'
              %h3.iblc 제목 : #{@video.title}
            %p.content-spec__text
              내용 : #{@video.body}
            %p.content-spec__text
              = @video.link
            %p.content-spec__text
              - if @video.owner_name
                권리자 : #{@video.owner_name}
                (
                = link_to @video.check_owner_url, @video.check_owner_url
                )
            .content-spec__copyright
              - if @video.extra_copyright
                = link_to (@video.copy_right_image_url), @video.copy_right_licence_info_url
              - else
                = link_to image_tag(@video.copy_right_image_url), @video.copy_right_licence_info_url
          .content-main__download.content-download
            %ul.content-download__list
              - if @video.download_links_hash.present?
                - @video.download_links_hash.each do |down|
                  %li.content-size{"data-download-url" => video_download_path(@video, type_quality: down["quality"], type_width: down["width"])}
                    %input.content-size__radio{:type => "radio", name: "video_radio", value: down["quality"]}
                    %span.content-size__option
                      = "#{down['width']} X #{down['height']}"
                    %span.content-size__type
                      = down["type"]
                .content-download__button.text-center
                  %a{:href => "#", :role => "button", :class => "iblc"} 다운로드
              - else
                .text-center
                  %br
                  = '다운로드를 제공하지 않습니다.'
    .content
      .content-box
        %h4.content-box__title
          ="키워드"
        %p.content-box__description
          - if @video.tags
            - @video.tags.each do |tag|
              %span.label.label-default
                = link_to tag.name, [:tags, :contents, tag: tag.name]

      - if @friendly_videos.present?
        .content-box
          %h4.content-box__title
            ="관련 비디오"
          .content-box__imglist.content-imglist
            .img-list.als-container
              %span.als-prev
                = image_tag 'icon-arrow-left.png', alt: '왼쪽버튼'
              .als-viewport
                %ul.als-wrapper
                  - @friendly_videos.each do |fr_video|
                    %li.als-item
                      = link_to image_tag(fr_video.thumbnail_url), fr_video
              %span.als-next
                = image_tag 'icon-arrow-right.png', alt: '오른쪽버튼'
            .clearfix
      - if @author_videos.present?
        .content-box
          %h4.content-box__title
            ="작가의 최신 비디오"
          .content-box__imglist.content-imglist
            .img-list.als-container
              %span.als-prev
                = image_tag 'icon-arrow-left.png', alt: '왼쪽버튼'
              .als-viewport
                %ul.als-wrapper
                  - @author_videos.each do |author_video|
                    %li.als-item
                      = link_to image_tag(author_video.thumbnail_url), author_video
              %span.als-next
                = image_tag 'icon-arrow-right.png', alt: '오른쪽버튼'
            .clearfix
      - if current_user.admin?
        .content-box.content-activity
          %h4.content-box__title
            다운로드 정보
          %p= "다운로드 횟수 : #{@activities.count}회"
          %p= link_to "이 컨텐츠의 다운로드 현황 보러가기", [:admin, :user_activities, content_id: @video.id]
  .text-center
    = link_to '목록으로', [:admin, :videos], class: 'btn btn-default'
    = link_to '수정하기', [:edit, :admin, @video], class: 'btn btn-default' if can? :update, @video
    = link_to '삭제하기', [:admin, @video], method: 'delete', data: {  confirm: '정말 삭제하시겠습니까?' }, class: 'btn btn-default'  if can? :destroy, @video

  :javascript
    $(function() {
      $(".content-download").on("change", "input.content-size__radio", function(e) {
        var $wrapper = $(e.delegateTarget);
        var url = $(this).parent("li.content-size").data("download-url");
        $wrapper.find('.content-download__button a').attr("href", url);
      });
    });

app/views/admin/videos/toggle_main.js.erb
if (<%= @video.main %> == true){
  $('.main_td#video_<%= @video.id %>').find('p').html('<p>true</p>');
} else if (<%= @video.main %> == false){
  $('.main_td#video_<%= @video.id %>').find('p').html('<p>false</p>');
}

app/views/admin/videos/toggle_open.js.erb
if (<%= @video.is_open %> == true){
  $('.is_open_td#video_<%= @video.id %>').find('p').html('<p>true</p>');
} else if (<%= @video.is_open %> == false){
  $('.is_open_td#video_<%= @video.id %>').find('p').html('<p>false</p>');
}